### ISSUE TITLE
Unable to unregister from an iOS Device, Also Ring and other operations not working.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#568] opened 2017-05-31 09:09 UTC
We are not able to unregister from EMM iOS App.

 Registration went successful and we are able to apply certain policies to device and also able to lock the device.

 Ring operation not working as well.

 <p>Reference: <a href='https://wso2.org/jira/browse/IOTS-449'>https://wso2.org/jira/browse/IOTS-529</a></p>

**Comment by inoshperera** [comment] 2017-06-13 10:18
@milanperera Please verify if the above issues are fixed in latest releases

**Comment by milanperera** [comment] 2017-06-28 11:12
This has been tested in the latest IoT 3.1.0 alpha pack and it works as expected.

**Comment by chamaraanu** [comment] 2017-06-29 09:09
Which version of iOS did you check this with? 
I checked with 10.1.1 and I encountered that ring and other operations are not working..

**Comment by milanperera** [comment] 2017-06-29 10:02
@chamaraanu  Were you able to enroll the device without any issue?
If so, the issue is with your APNS certificate.

**Closed as completed** 2017-07-22 05:27 UTC
Labels: Type/Bug
