### ISSUE TITLE
[IOTS-219] Startup API publication fails when default AdminUser credentials are changed

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#645] opened 2017-06-05 03:58 UTC
Startup API publication fail when default AdminUser credentials are changed. Following errors are thrown. the credentials were changed in files listed below in addition to user-mgt.xml for verification.  repository/conf/etc/tasks-config.xml:43: repository/conf/user-mgt.xml:23: repository/conf/analytics/analytics-data-config.xml:38: repository/conf/cdm-config.xml:34: repository/conf/api-manager.xml:74: repository/conf/api-manager.xml:156: repository/conf/api-manager.xml:227: repository/conf/api-manager.xml:287: repository/conf/api-manager.xml:485: repository/conf/security/authenticators.xml:33: repository/conf/broker.xml:126   [2016-06-08 14:19:26,305] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'virtual_firealarm' [2016-06-08 14:19:26,308] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'raspberrypi' [2016-06-08 14:19:26,309] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Device Search' [2016-06-08 14:19:26,311] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'License' [2016-06-08 14:19:26,313] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Group' [2016-06-08 14:19:26,314] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Device Search' [2016-06-08 14:19:26,316] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Certificate' [2016-06-08 14:19:26,318] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Device Information' [2016-06-08 14:19:26,320] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Profile' [2016-06-08 14:19:26,322] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Configuration' [2016-06-08 14:19:26,323] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'User' [2016-06-08 14:19:26,325] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Device Notification' [2016-06-08 14:19:26,326] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Role' [2016-06-08 14:19:26,327] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Device' [2016-06-08 14:19:26,328] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Operation' [2016-06-08 14:19:26,330] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'Policy' [2016-06-08 14:19:26,332] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'arduino' [2016-06-08 14:19:26,333] ERROR - APIPublisherStartupHandler Error occurred while publishing API 'android_sense' [2016-06-08 14:19:35,463] WARN - CarbonAuthenticationUtil Failed Administrator login attempt 'password[-1234]' at [2016-06-08 14:19:35,462+0530] [2016-06-08 14:19:35,466] WARN - AuthenticationHandler Illegal access attempt at [2016-06-08 14:19:35,0466] from IP address 127.0.0.1 while trying to authenticate access to service OAuth2TokenValidationService [2016-06-08 14:19:35,469] ERROR - OAuth2BasedMQTTAuthenticator Error on connecting with the validation endpoint. org.apache.axis2.AxisFault: Access Denied. Authentication failed - Invalid credentials provided. at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531) at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:370) at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:445) at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225) at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) at org.wso2.carbon.identity.oauth2.stub.OAuth2TokenValidationServiceStub.validate(OAuth2TokenValidationServiceStub.java:461) at org.wso2.carbon.andes.authentication.andes.OAuth2BasedMQTTAuthenticator.getAuthenticationInfo(OAuth2BasedMQTTAuthenticator.java:126) at org.wso2.carbon.andes.authentication.andes.OAuth2BasedMQTTAuthenticator.validateToken(OAuth2BasedMQTTAuthenticator.java:82) at org.wso2.carbon.andes.authentication.andes.OAuth2BasedMQTTAuthenticator.checkValid(OAuth2BasedMQTTAuthenticator.java:62) at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:256) at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:160) at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:47) at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) [2016-06-08 14:19:35,518] WARN - CarbonAuthenticationUtil Failed Administrator login attempt 'password[-1234]' at [2016-06-08 14:19:35,518+0530] [2016-06-08 14:19:35,518] WARN - AuthenticationHandler Illegal access attempt at [2016-06-08 14:19:35,0518] from IP address 127.0.0.1 while trying to authenticate access to service OAuth2TokenValidationService [2016-06-08 14:19:35,521] ERROR - OAuth2BasedMQTTAuthenticator Error on connecting with the validation endpoint. org.apache.axis2.AxisFault: Access Denied. Authentication failed - Invalid credentials provided. at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531) at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:370) at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:445) at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225) at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) at org.wso2.carbon.identity.oauth2.stub.OAuth2TokenValidationServiceStub.validate(OAuth2TokenValidationServiceStub.java:461) at org.wso2.carbon.andes.authentication.andes.OAuth2BasedMQTTAuthenticator.getAuthenticationInfo(OAuth2BasedMQTTAuthenticator.java:126) at org.wso2.carbon.andes.authentication.andes.OAuth2BasedMQTTAuthenticator.validateToken(OAuth2BasedMQTTAuthenticator.java:82) at org.wso2.carbon.andes.authentication.andes.OAuth2BasedMQTTAuthenticator.checkValid(OAuth2BasedMQTTAuthenticator.java:62) at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:256) at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:160) at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:47) at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) .... .... [2016-06-08 14:35:09,974] ERROR - MQTTAdapterListener MQTT Exception occurred when starting listener Bad user name or password (4) at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28) at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:885) at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:118) at java.lang.Thread.run(Thread.java:745)<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-219'>https://wso2.org/jira/browse/IOTS-219</a></p>

**Comment by geethkokila** [comment] 2017-06-13 09:10
This is fixed and tested in the IoT server 3.1.0. Hence closing.

**Closed as completed by geethkokila** 2017-06-13 09:10 UTC
Labels: Type/Bug, normal

**Comment by iScorpio** [comment] 2018-06-22 10:06
The cause for this bug
https://github.com/wso2/carbon-device-mgt-plugins/issues/907
