### ISSUE TITLE
[IOTS-440] Intermittent issue with Android oauth token generation

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#603] opened 2017-06-05 03:46 UTC
Following error comes when device tryies to get the oauth token using refresh token. EMM Console Error TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,503&#93; DEBUG  {org.wso2.carbon.identity.oauth2.OAuth2Service} - Access Token request received for Client ID U1lGY0tEVWAdKyWgWg8MlGlQLcAa, User ID null, Scope : &#91;PRODUCTION&#93; and Grant Type : refresh_token  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,504&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.clientauth.AbstractClientAuthHandler} - Can authenticate with client ID and Secret. Client ID: U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,505&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.clientauth.AbstractClientAuthHandler} - Grant type : refresh_token Strict client validation set to : null  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,505&#93; DEBUG {org.wso2.carbon.identity.oauth2.util.OAuth2Util} - Client credentials were available in the cache for client id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,506&#93; DEBUG {org.wso2.carbon.identity.oauth2.util.OAuth2Util} - Successfully authenticated the client with client id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,509&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler} - Access Token is not in 'ACTIVE' or 'EXPIRED' state for Client with Client Id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,510&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - Invalid Grant provided by the client Id: U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:25:31,510&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - OAuth-Error-Code=invalid_grant client-id=U1lGY0tEVWAdKyWgWg8MlGlQLcAa grant-type=refresh_token scope=PRODUCTION  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:11,990&#93; DEBUG {org.wso2.carbon.identity.oauth2.OAuth2Service}  - Access Token request received for Client ID U1lGY0tEVWAdKyWgWg8MlGlQLcAa, User ID null, Scope : &#91;PRODUCTION&#93; and Grant Type : refresh_token  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:11,991&#93; DEBUG  {org.wso2.carbon.identity.oauth2.token.handlers.clientauth.AbstractClientAuthHandler} - Can authenticate with client ID and Secret. Client ID: U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:11,992&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.clientauth.AbstractClientAuthHandler}  - Grant type : refresh_token Strict client validation set to : null  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:11,992&#93; DEBUG  {org.wso2.carbon.identity.oauth2.util.OAuth2Util} - Client credentials were available in the cache for client id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:11,992&#93; DEBUG {org.wso2.carbon.identity.oauth2.util.OAuth2Util}  - Successfully authenticated the client with client id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:12,001&#93; DEBUG  {org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler} - Access Token is not in 'ACTIVE' or 'EXPIRED' state for Client with Client Id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:12,002&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - Invalid Grant provided by the client Id: U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:12,002&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - OAuth-Error-Code=invalid_grant client-id=U1lGY0tEVWAdKyWgWg8MlGlQLcAa grant-type=refresh_token scope=PRODUCTION  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,580&#93; DEBUG {org.wso2.carbon.identity.oauth2.OAuth2Service} - Access Token request received for Client ID U1lGY0tEVWAdKyWgWg8MlGlQLcAa, User ID null, Scope : &#91;PRODUCTION&#93; and Grant Type : refresh_token  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,581&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.clientauth.AbstractClientAuthHandler} - Can authenticate with client ID and Secret. Client ID: U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,581&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.clientauth.AbstractClientAuthHandler} - Grant type : refresh_token Strict client validation set to : null  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,582&#93; DEBUG {org.wso2.carbon.identity.oauth2.util.OAuth2Util} - Client credentials were available in the cache for client id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,582&#93; DEBUG {org.wso2.carbon.identity.oauth2.util.OAuth2Util} - Successfully authenticated the client with client id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,585&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler}  - Access Token is not in 'ACTIVE' or 'EXPIRED' state for Client with Client Id : U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,585&#93; DEBUG  {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - Invalid Grant provided by the client Id: U1lGY0tEVWAdKyWgWg8MlGlQLcAa  TID: &#91;-1234&#93; [] &#91;2016-11-04 09:26:29,586&#93; DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer}  - OAuth-Error-Code=invalid_grant client-id=U1lGY0tEVWAdKyWgWg8MlGlQLcAa grant-type=refresh_token scope=PRODUCTION  NGINX log.  103.21.166.25 - U1lGY0tEVWAdKyWgWg8MlGlQLcAa &#91;04/Nov/2016:09:15:31 +0000&#93; "POST /oauth2/token HTTP/1.0" 400 87 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0; E2363 Build/26.1.B.3.109)" 103.21.166.25 - U1lGY0tEVWAdKyWgWg8MlGlQLcAa &#91;04/Nov/2016:09:15:31 +0000&#93; "POST /oauth2/token HTTP/1.0" 400 87 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0; E2363 Build/26.1.B.3.109)" 103.21.166.25 - U1lGY0tEVWAdKyWgWg8MlGlQLcAa &#91;04/Nov/2016:09:16:13 +0000&#93; "POST /oauth2/token HTTP/1.0" 400 87 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0; E2363 Build/26.1.B.3.109)" ^C<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-440'>https://wso2.org/jira/browse/IOTS-440</a></p>

**Comment by geethkokila** [comment] 2017-06-13 09:49
This is fixed with changes to agent source code. The issue was when regenerating the OAuth token with refresh token, if it takes longs time, agent times out. when that happens, the agent cannot use the same refresh token again, the server will return 400, therefore it will cause the above issue. 

The issue is fixed with increased timeout value for regenerating token, and the user is given a chance to reenter the username and password.

**Closed as completed by geethkokila** 2017-06-13 09:49 UTC
Labels: Type/Bug, high
