### ISSUE TITLE
[EMM-1872] Nexus 5x and Google Pixel go inactive and don't recover

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#526] opened 2017-05-31 08:29 UTC
After enrolling the Nexus or Pixel running 7.x, 5 hours later both test devices went inactive and cannot recover by rebooting or opening the Android agent. App still says "Registered".            Unregistering on both devices does not work within the Android device agent. I have to manually uninstall the application and start over.                           Pixel 1:                              Enrolled POLICY_BUNDLECompleted2017-02-09 11:39                              Went Inactive: MONITORPending2017-02-09 13:59                                       Pixel 2:                              Enrolled POLICY_BUNDLECompleted2017-02-09 11:41                              Went Inactive: APPLICATION_LISTPending2017-02-09 15:39                        Haven't seen these issues with MotoG running 6.0.1 or 7.0.1.         
<p>Reference: <a href='https://wso2.org/jira/browse/EMM-1872'>https://wso2.org/jira/browse/EMM-1872</a></p>

**Comment by inoshperera** [comment] 2017-06-13 09:48
This is not reproducible.

**Comment by sinthuja** [comment] 2017-08-28 09:51
Jason is trying to reproduce the issue.

**Comment by sinthuja** [comment] 2017-08-28 11:16
Jason was not reproduce this issue in my One plus 3 phone as well, with latest IoT server distribution. And hence resolving this issue as we are unable to reproduce this issue.

**Closed as completed by sinthuja** 2017-08-28 11:16 UTC
Labels: Type/Bug, medium
