### ISSUE TITLE
Web clip uninstallation doesn't work in Android

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#408] opened 2017-05-05 06:55 UTC
When a webclip uninstall command is issued after installing a web clip. The operation does not remove the webclip, but it is shown as completed in the UI

https://wso2.org/jira/browse/IOTS-527

**Comment by inoshperera** [comment] 2017-06-14 07:21
Tested this on jelly beans(SDK int 17) and it works as expected. Tested this issue on device running 6.0.1 and the issue was reproduced. However, further digging revealed that Google has removed support for shortcut uninstallation, due to the fact that this feature is poorly designed, causing any app being able to delete any other app's shortcut. Therefore closing the issue
AOSP commit -https://android.googlesource.com/platform/packages/apps/Launcher3/+/e9909f58c2b235f8066295c4faa6a00415968ae7
Diff - https://android.googlesource.com/platform/packages/apps/Launcher3/+/e9909f58c2b235f8066295c4faa6a00415968ae7%5E%21/#F2

**Closed as completed by inoshperera** 2017-06-14 07:21 UTC
Labels: Type/Bug, high, 3.1.0-M6
