### ISSUE TITLE
Remote Controlling is not working for BYOD 

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/product-iots#1569] opened 2018-01-05 01:40 UTC
**Description:**
When clicking on 'connect device' button in Remote Session tab device doesn't connect. Further when we check operation log, 'REMOTE_CONNECT' operation is completed. 

- Tested in IoTS 3.1.0 update9

**Suggested Labels:**
Bug

**Affected Product Version:**
IoTS 3.1.0 Update9

**OS, DB, other environment details and versions:**    
OS - Ubuntu
Browser - Chrome and Firefox
DB - H2

**Steps to reproduce:**
Enroll BYOD device into IoTS update9
Click on 'connect device' button in Remote Session tab. 
![screenshot from 2018-01-05 07-04-47](https://user-images.githubusercontent.com/7247568/34592032-62204b9c-f1e7-11e7-9f38-8f85475467ea.png)

**Comment by inoshperera** [comment] 2018-01-17 02:59
Duplicate of https://github.com/wso2/product-iots/issues/1564

**Closed as completed by inoshperera** 2018-01-17 02:59 UTC
Labels: Type/Bug, Priority/High
