### ISSUE TITLE
[IOTS-439] Unable to blacklist applications in enrolled devices through an android policy

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#573] opened 2017-05-31 10:52 UTC
When few public application packages were included in an android policy as blacklist, it still visible to users and allow to use the applications. == Steps == 1. Enroll few android devices as both BYOD and COPE (with sys app) 2. Logged into EMM console, go to 'Applications Restrctions' in add policy for android. 3. Select type as 'Blacklist" and add few applications with name and package name.  4. Publish the policy and applied to enrolled devices. 5. Try to install the applications in enrolled devices and it should be successfully happen. But users can see the applications in app list and menu and even they can use the "black-listed apps"<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-439'>https://wso2.org/jira/browse/IOTS-439</a></p>

**Comment by inoshperera** [comment] 2017-06-13 12:33
Duplicate of https://github.com/wso2/product-iots/issues/669

**Closed as completed by inoshperera** 2017-06-13 12:33 UTC
Labels: Type/Bug, medium
