### ISSUE TITLE
Installed Android Agent on OnePlus3T phone - it does not sync to the server

### ISSUE THREAD

**Issue by vsafin** [wso2/product-iots#1223] opened 2017-07-24 22:37 UTC
When I click Syncronize button it spins and stops by label still says Synchronizing...

Server does not receive data from the Agent

**Comment by milanperera** [comment] 2017-08-06 18:09
Did you just download the agent from the IoT server itself or have you built it from the source?
Either way, you'll be able to plug the device into USB and can see the debug logs from logcat to check whether the device is getting updates from the server.
Also, it would be great if you can tell us the IoT server version you used? Is it built from the master branch or you just downloaded it from the release candidates list?

**Comment by charithag** [comment] 2017-08-30 06:35
@vsafin, I'm closing this issue, as we can't reproduce this with current development branch. Please feel free to reopen this issue with above requested details, if you are still experiencing this.

**Closed as completed by charithag** 2017-08-30 06:35 UTC
