### ISSUE TITLE
cannot open devicemgt

### ISSUE THREAD

**Issue by hammoudeh** [wso2/product-iots#296] opened 2017-02-27 23:00 UTC
Hi,
I just upgrade to IOT 3.0.0, but when I'm trying to open `https://localhost:9443/devicemgt` it redirect me to `https://localhost:9443/devicemgt/uuf/login?referer=/`

And show below message in internet explorer, and blank page in chrome and firefox. 

```
You are now being redirected to Identity Server. If the redirection fails, please click on the button below. 
   Redirect manually 
```

Finally: below the latest line in console: 
```

[2017-02-27 14:54:12,384] []  INFO - NioSelectorPool Using a shared selector for servlet write/read
[2017-02-27 14:54:12,431] []  INFO - NioSelectorPool Using a shared selector for servlet write/read
[2017-02-27 14:54:12,571] []  INFO - TaskServiceImpl Task service starting in STANDALONE mode...
[2017-02-27 14:54:12,587] []  INFO - DeviceTaskManagerServiceImpl Task adding for android
[2017-02-27 14:54:12,681] []  INFO - AbstractQuartzTaskManager Task scheduled: [-1234][DEVICE_MONITORING][android-1234]
[2017-02-27 14:54:12,681] []  INFO - DeviceTaskManagerServiceImpl Task adding for windows
[2017-02-27 14:54:12,696] []  INFO - AbstractQuartzTaskManager Task scheduled: [-1234][DEVICE_MONITORING][windows-1234]
[2017-02-27 14:54:12,837] []  INFO - RegistryEventingServiceComponent Successfully Initialized Eventing on Registry
[2017-02-27 14:54:12,962] []  INFO - JMXServerManager JMX Service URL  : service:jmx:rmi://localhost:11111/jndi/rmi://lo
calhost:9999/jmxrmi
[2017-02-27 14:54:12,962] []  INFO - URLPrinterStartupHandler IoT Console URL : https://localhost:9443/devicemgt
[2017-02-27 14:54:12,978] []  INFO - StartupFinalizerServiceComponent Server           :  WSO2 IoT Server-3.0.0
[2017-02-27 14:54:12,978] []  INFO - StartupFinalizerServiceComponent WSO2 Carbon started in 83 sec
[2017-02-27 14:54:13,290] []  INFO - CarbonUIServiceComponent Mgt Console URL  : https://localhost:9443/carbon/
```

**Comment by hammoudeh** [comment] 2017-03-06 08:30
any update here ?

**Comment by ayyoob** [comment] 2017-03-06 14:39
Are you trying on windows OS?, If it is then start the server with the below command. This issue is fixed on the latest pack

.\wso2server.bat -Diot.analytics.host="localhost" -Diot.analytics.https.port="9445" -Dmqtt.broker.host="localhost" -Dmqtt.broker.port="1886" -Diot.core.host="localhost" -Diot.core.https.port="9443" -Diot.keymanager.host="localhost" -Diot.keymanager.https.port="9443" -Diot.gateway.host="localhost" -Diot.gateway.https.port="8243" -Diot.gateway.http.port="8280"

**Comment by hammoudeh** [comment] 2017-03-06 20:56
Nothing changed.

**Comment by ayyoob** [comment] 2017-03-06 21:12
above command will work on fresh pack. if you want to make it work on existing pack then enable UpdateAPI(set true to EnableUpdateApi property) in webapp-publisher-config.xml in core/repository/conf/etc directory.

The reason for the above change is because from IoTS 3.0.0, all the apis are published to the gateway and this happens during first time. enabling above mentioned properly will allow to publish the apis again

**Comment by yujie123jw** [comment] 2017-03-07 06:21
IoTS 3.0.0 installed in Linux CentOS 6.5 has the same problem。

**Comment by yujie123jw** [comment] 2017-03-07 08:11
this  is  big  bug !!
As follow  url 's solution  .
https://docs.wso2.com/display/IoTS300/Configuring+WSO2+IoT+Server+with+the+IP

**Comment by hammoudeh** [comment] 2017-03-07 10:07
@yujie123jw is this the solution ? 

Actually I follow the the steps there, but it's not working. 
I installed in windows server 2012. 

@ayyoob still same problem, even in  3.1.0-M1

**Comment by ayyoob** [comment] 2017-03-07 12:58
@yujie123jw IoTS by default binds with localhost because it comes with sso enabled. If you are working on a remote server then the suggested changes need to be done.

@hammoudeh This bug is not fixed in M1, it will be fixed on M2.

**Comment by hammoudeh** [comment] 2017-03-07 13:01
@ayyoob thank you. When can I expect M2 release ?

**Comment by ayyoob** [comment] 2017-03-07 14:21
There is a plan to do a release on 15th of March

**Comment by yujie123jw** [comment] 2017-03-07 14:44
@hammoudeh  just display  login view.

Additional:

Actually I follow the the steps there,i try again  can completed  firealarm example. 

But there are still small bug,for example,

        <div class="panel-heading">Device Statistics</div>
        <div id="div-chart" data-websocketurl="wss://localhost:9445/secured-websocket/org.wso2.iot.devices.temperature/1.0.0?deviceId=trzmqsvrh9h4&amp;deviceType=virtual_firealarm">

**Comment by emileyi** [comment] 2017-03-30 08:13
@ayyoob I can't start M2 in Windows and Linux, and there is bug in iot-server.bat .

**Comment by sinthuja** [comment] 2017-03-30 09:13
@emileyi Sorry for the inconvenience caused, and yeah there is an issue in the iot-server.bat, and currently, we are working on fixing that. But we haven't encountered any startup issues with Linux, and sh files works as expected. Can you please give us some more details about the issues that you have faced? It will be helpful, if you could provide the steps to reproduce the error and exception trace/error log anything that you have got during this test.

**Comment by emileyi** [comment] 2017-04-01 07:25
Sorry, I changed to another OS, it's OK. Before it's redhat (log : org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: redhat: redhat")

**Comment by sinthuja** [comment] 2017-04-06 05:38
@emileyi , Great to hear that you got working on another OS. With regard to the issue that you have experienced with redHat, I suspect that your localhost name is 'redHat', and it's not added into the /etc/hosts. Generally, it's added by default by pointing to localhost IP (127.0.0.1). In case, if it's not, you can manually add it and try to restart the WSO2 server.

**Comment by geethkokila** [comment] 2017-06-13 11:33
Please reopen if you need a further assistant on this issue.

**Closed as completed by geethkokila** 2017-06-13 11:33 UTC
