### ISSUE TITLE
[IOTS-496] UI shows incorrect device list on user list page for a given user

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#616] opened 2017-06-05 03:56 UTC
Enrolled devices by user displays the devices by other users.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-496'>https://wso2.org/jira/browse/IOTS-496</a></p>

**Comment by sinthuja** [comment] 2017-08-28 07:16
@Nirothipan Will verfiy.

**Comment by Nirothipan** [comment] 2017-08-28 09:38
This issue is not reproduced in IoTs 3.1.0. 
I created a new user and enrolled a device with that user.
Enrolled devices by user displayed the correct device lists for both users (admin and newly created one).
Hence closed.

**Comment by sinthuja** [comment] 2017-08-28 09:39
Closing this issue as this cannot be reproduced.

**Comment by sinthuja** [comment] 2017-08-28 09:52
Pubudu is trying to reproduce this issue.

**Comment by pubudup** [comment] 2017-08-28 12:53
@sinthuja 

I was able to reproduce the issue by running the attached two scripts concurrently on a fresh IoT 3.1.0 GA build.
 It looks like the issue happens If User A registers device A with device identifier ID1 and User B registers device B with device identifier ID1 then User A's device A is listed under user B's registered devices. We should add relevant validation for this.
[IoT.zip](https://github.com/wso2/product-iots/files/1256774/IoT.zip)

**Comment by Nirothipan** [comment] 2017-08-29 12:20
Hi all,

I could reproduce this issue in IoT server 3.0.0.
I created 2 users ( user1 and user2 ) and enrolled one device for each user ( device 1 and device2 respectively), as mentioned in the ticket, I could able to view the device1 in user2 and device 2 in user1.

This issue is fixed in IoT server 3.1.0 and no longer present.
Hence this can be closed.

Thank you.

**Closed as completed** 2017-08-29 12:32 UTC
Labels: Type/Bug, normal, Automation-Test-Needed
