### ISSUE TITLE
[MDM-367] Proper "Error" message is not given when trying to invite a user without having the email transport properly configured.

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#504] opened 2017-05-30 06:40 UTC
<p>Instead, the message pops up in the console says "User invitation has successfully been sent", which is misleading.</p><p>Following error, though, is thrown and logged on the console.</p><p><span class="error">&#91;2015-07-17 17:14:33,611&#93;</span>  INFO </p>{org.wso2.carbon.ui.internal.CarbonUIServiceComponent}<p> -  Mgt Console URL  : <a href="https://10.100.1.206:9443/carbon/" class="external-link" rel="nofollow">https://10.100.1.206:9443/carbon/</a><br/><span class="error">&#91;2015-07-17 17:38:07,286&#93;</span> ERROR </p>{org.wso2.carbon.device.mgt.core.email.sender.EmailServiceProviderImpl} -  Error in delivering the message, subject: 'Enroll your Device with WSO2 MDM', to: 'prabatha@wso2.com'<br/>org.apache.axis2.AxisFault: The system cannot infer the transport information from the <span class="nobr"><a href="mailto:prabatha@wso2.com" class="external-link" rel="nofollow">prabatha@wso2.com<sup><img class="rendericon" src="https://wso2.org/jira/images/icons/mail_small.gif" height="12" width="13" align="absmiddle" alt="" border="0"/></sup></a></span> URL.<br/>at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81)<br/>at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)<br/>at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249)<br/>at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)<br/>at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511)<br/>at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488)<br/>at org.wso2.carbon.device.mgt.core.email.sender.EmailServiceProviderImpl$EmailSender.run(EmailServiceProviderImpl.java:109)<br/>at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/>at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>at java.lang.Thread.run(Thread.java:745)<br/><span class="error">&#91;2015-07-17 17:38:16,749&#93;</span> ERROR {org.wso2.carbon.device.mgt.core.email.sender.EmailServiceProviderImpl}<p> -  Error in delivering the message, subject: 'Enroll your Device with WSO2 MDM', to: 'prabatha@wso2.com'<br/>org.apache.axis2.AxisFault: The system cannot infer the transport information from the <span class="nobr"><a href="mailto:prabatha@wso2.com" class="external-link" rel="nofollow">prabatha@wso2.com<sup><img class="rendericon" src="https://wso2.org/jira/images/icons/mail_small.gif" height="12" width="13" align="absmiddle" alt="" border="0"/></sup></a></span> URL.<br/>at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81)<br/>at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)<br/>at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249)<br/>at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)<br/>at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511)<br/>at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488)<br/>at org.wso2.carbon.device.mgt.core.email.sender.EmailServiceProviderImpl$EmailSender.run(EmailServiceProviderImpl.java:109)<br/>at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/>at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>at java.lang.Thread.run(Thread.java:745)</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-367'>https://wso2.org/jira/browse/MDM-367</a></p>

**Comment by sinthuja** [comment] 2017-08-28 08:09
@Nirothipan will check this.

**Comment by Nirothipan** [comment] 2017-08-29 13:49
Hi all,

This issue was reproduced in IoT 3.0.0 but in 3.1.0 we don't have an option to invite a user as such in 3.0.0.
Hence not applicable and can be closed.

Thank you.

**Comment by sinthuja** [comment] 2017-08-30 12:10
Closing this issue as the issue is fixed.

**Closed as completed by sinthuja** 2017-08-30 12:10 UTC
Labels: Type/Bug, medium
