### ISSUE TITLE
[IOTS-452] Device shows inactive after long power off

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#590] opened 2017-06-05 02:53 UTC
After enrolling a device (Nexus 5x) ver 7.1.1 powering off the device shows the phone "Inactive" in the MDM dashboard. After powering on device and waiting 15 minutes the device still says "Inactive".<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-452'>https://wso2.org/jira/browse/IOTS-452</a></p>

**Comment by inoshperera** [comment] 2017-06-20 12:34
Tested on Android SDK 17 and the issue is not reproducible. As the JIRA suggest, the issue is possibly due to having the battery saving mode enabled. Battery saving mode cannot be turned off without having root privileges. Therefore, closing the ticket.

**Closed as completed by inoshperera** 2017-06-20 12:34 UTC
Labels: Type/Bug, high
