### ISSUE TITLE
[APPM-1637] Sign-in from secondary user store causes solr exception

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#826] opened 2017-06-06 07:31 UTC
<p>Reference: <a href='https://wso2.org/jira/browse/APPM-1637'>https://wso2.org/jira/browse/APPM-1637</a></p>

**Comment by Megala21** [comment] 2017-08-29 04:44
This is a duplicate of #827 . Hence closing this issue.

**Closed as completed by Megala21** 2017-08-29 04:44 UTC
Labels: Type/Bug, duplicate, medium
